#ifndef SECRETS_H
#define SECRETS_H

// 1. WiFi Credentials
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// 2. Firebase Credentials
#define DATABASE_SECRET "YOUR_FIREBASE_DATABASE_SECRET"
#define DATABASE_URL "YOUR_FIREBASE_DATABASE_URL"

#endif

